openapi: 3.1.0
info:
  description: The master list api allows you to fetch data from the alt:V master list service.
  version: 15.3.0
  title: altv-masterlist
  termsOfService: https://altv.mp/terms-of-service.pdf
  contact:
    email: contact@alt-mp.com
  license:
    name: Mozilla Public License 2.0
    url: https://github.com/Nickwasused/altv-masterlist-swagger/blob/main/LICENSE
paths:
  /servers/info:
    get:
      tags:
      - "stats"
      summary: Statistics
      description: Statistics - Player Count across all servers & The amount of servers online
      operationId: servers
      responses:
        '200':
          description: Server Statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerStats'
          
  /servers:
    get:
      tags:
      - "server"
      summary: Server List
      description: Servers - All information known about all servers (Name, Description, IP, Language, Website, Etc.)
      operationId: servers-list
      responses:
        '200':
          description: A Server Object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerList'
          
  "/server/{MASTERLIST_ID}":
    get:
      tags:
      - "server"
      summary: server
      description: Specific Server - Filters server list for a specific one. Uses "id" which is unique to the server token
      operationId: server
      parameters:
        - name: MASTERLIST_ID
          in: path
          description: ID which is unique to the server token
          required: true
          schema:
            type: string
            pattern: '^[a-zA-Z0-9]{7}$'
            format: string
      responses:
        '200':
          description: A Server Object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Server'
          
  "/avg/{MASTERLIST_ID}/{TIME}":
    get:
      tags:
      - "stats"
      summary: average
      description: Averages - Returns averages data about the specified server (TIME = 1d, 7d, 31d)
      operationId: average
      parameters:
        - name: MASTERLIST_ID
          in: path
          description: ID which is unique to the server token
          required: true
          schema:
            type: string
            pattern: '^[a-zA-Z0-9]{7}$'
            format: string
        - name: TIME
          in: path
          description: TIME = 1d, 7d, 31d
          required: true
          schema:
            type: string
            format: string
            pattern: '^(1d)|(7d)|(31d)|(1D)|(7D)|(31D)$'
      responses:
        "200":
          description: api responded
          
  "/max/{MASTERLIST_ID}/{TIME}":
    get:
      tags:
      - "stats"
      summary: maximum
      description: Maximum - Returns maximum data about the specified server (TIME = 1d, 7d, 31d)
      operationId: maximum
      parameters:
        - name: MASTERLIST_ID
          in: path
          description: ID which is unique to the server token
          required: true
          schema:
            type: string
            pattern: '^[a-zA-Z0-9]{7}$'
            format: string
        - name: TIME
          in: path
          description: TIME = 1d, 7d, 31d
          required: true
          schema:
            type: string
            format: string
            pattern: '^(1d)|(7d)|(31d)|(1D)|(7D)|(31D)$'
      responses:
        "200":
          description: api responded

components:
  schemas:
    Server:
      type: object
      properties:
        ip:
          type: ipv4
          description: The ip adress of the server
        playersCount:
          type: integer
          description: The current amount of Players on the Server.
        maxPlayersCount:
          type: integer
          description: The Maximum amount of Players that can play.
        passworded:
          type: boolean
          description: State of Server password protection.
        port:
          type: integer
          format: port
          description: The Server Port
        language:
          type: string
          description: The Server language as short code. E.g. "en", "de"
        useEarlyAuth:
          type: boolean
          description: State of EarlyAuth Authentication of a Server.
        earlyAuthCdn:
          type: string
          format: uri
          description: The URL of the Early Auth Frontend
        useCdn:
          type: boolean
          description: State of Server CDN
        cdnUrl:
          type: string
          format: uri
          description: The URL of the Server CDN. Resource List = CDN_URL + /connect.json
        useVoiceChat:
          type: boolean
          description: State of Server Voice Chat
        version:
          type: string
          description: the alt:V Version of the server
        branch:
          type: string
          description: the alt:V Branch of the server e.g. release, dev, rc
        available:
          type: boolean
          description: offline/online status of the server?
        banned:
          type: boolean
          description: if the server is banned from alt:V
        name:
          type: string
          description: The Server Name
        publicId:
          type: string
          pattern: '^[a-zA-Z0-9]{7}$'
          description: The Server ID
        vanityUrl:
          type: string
          description: this id can be used with altv.run e.g. altv.run/homestate
        website:
          type: string
          format: uri
          description: The Server Website
        gameMode:
          type: string
          description: The Server Game mode
        description:
          type: string
          description: The Server description.
        tags:
          type: array
          items:
            type: string
          description: Server tags, e.g. "No Rules"
        lastTimeUpdate:
          type: string
          description: A timestamp when the Server last sent data. e.g. 2023-10-21T08:00:22.830909841Z
        verified:
          type: boolean
          description: State of Server verification. (A Server needs a certain amount of Players for that over a big timespan)
        promoted:
          type: boolean
          description: A Server needs at least a Diamond Altruist Membership.
        visible:
          type: boolean
          description: visibility status in the masterlist
        hasCustomSkin:
          type: boolean
          description: if the server has a custom skin
        bannerUrl:
          type: string
          format: uri
          description: The URL of the Server Banner. (A server needs at least a Ruby Altruist Membership for that.)
        address:
          type: string
          description: the connection adress of the server

    ServerList:
      type: array
      items:
        type: Server
            
    ServerStats:
      type: object
      properties:
        playersCount:
          type: integer
          description: The Amount of Players online
        serversCount:
          type: integer
          description: The Amount of Servers online
        totalPlayersCount:
          type: integer
          description: The Total Amount of Servers online
        totalServersCount:
          type: integer
          totalServersCount: The Total Amount of Players online

servers:
  - url: https://api.alt-mp.com/
  - url: https://api.altv.mp/
  
externalDocs:
  description: "Masterlist API Docs"
  url: "https://docs.altv.mp/articles/master_list_api.html"
