openapi: 3.1.0
info:
  description: altstats.net - alt:V Stats is a alternative server list, developed and supported by members of the altMP Team. It has additional statistics about servers like player count for the last 24 hours, 7 days or month and you have a server specific API. like showing the player count for the last month are premium features, you need to pay for them to enable them.
  version: 9.15.0
  title: altstats.net
  termsOfService: https://altv.mp/terms-of-service.pdf
  contact:
    email: contact@alt-mp.com
  license:
    name: Mozilla Public License 2.0
    url: https://github.com/Nickwasused/altv-masterlist-swagger/blob/main/LICENSE
paths:
  /api/v1/master:
    get:
      tags:
      - "stats"
      summary: Server Statistics
      description: Count - Shows the server and player count for the last 24 hours
      operationId: master
      responses:
        '200':
          description: Server Statistics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerStats'
          
  /api/v1/server:
    get:
      tags:
      - "server"
      summary: Server List
      description: Servers - Basic information about all known servers
      operationId: servers-list
      responses:
        '200':
          description: A Server Object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerList'
          
  "/api/v1/server/{serverID}":
    get:
      tags:
      - "server"
      summary: server
      description: Specific Server - Filters server list for a specific one. Uses "id" which is unique to the server token
      operationId: server
      parameters:
        - name: serverID
          in: path
          description: ID
          required: true
          schema:
            type: integer
            pattern: '^[0-9]{1,}$'
      responses:
        '200':
          description: A Server Object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Server'

components:
  schemas:
    Server:
      type: object
      properties:
        Id:
          type: integer
          pattern: '^[0-9]{1,}$'
          description: The Server ID
        FoundAt:
          type: string
          format: date-time
          description: Timestamp when the server got found by the API.
        LastActivity:
          type: string
          format: date-time
          description: Timestamp when the server was active.
        Visible:
          type: boolean
          description: Boolean if the Server is visible.
        ServerId:
          type: string
          pattern: '^[0-9a-zA-Z]{32}$'
          description: alt:V Server id
        Players:
          type: integer
          description: The current amount of Players on the Server.
        Name:
          type: string
          description: The Server Name
        Locked:
          type: boolean
          description: State of Server password protection.
        Ip:
          type: string
          format: ipv4
          description: The Server IP/Hostname
        Port:
          type: integer
          format: port
          description: The Server Port
        MaxPlayers:
          type: integer
          description: The Maximum amount of Players that can play.
        Ping:
          type: integer
          description: The Server Ping
        Website:
          type: string
          format: uri
          description: The Server Website
        Language:
          type: string
          description: The Server language as short code. E.g. "en", "de"
        Description:
          type: string
          description: The Server description.
        LastUpdate:
          type: integer
          description: Unix Timestamp of last Server update
        IsOfficial:
          type: boolean
          description: State of Server verification. (A Server needs a certain amount of Players for that over a big timespan)
        PlayerRecord:
          type: integer
          description: The Player Record of the Server
        PlayerRecordDate:
          type: string
          format: date-time
          description: The Timestamp of the Player Record
        LastFetchOnline:
          type: boolean
          description: Was the Server Online the last time.
        LanguageShort:
          type: string
          description: The Language Code in short form e.g. "de", "en", "gb"
        GameMode:
          type: string
          description: The Server Game mode
        Branch:
          type: string
          description: The Server Branch. E.g. release, dev.
        Build:
          type: integer
          description: This has been -1 for a long time.
        CdnUrl:
          type: string
          format: uri
          description: The URL of the Server CDN. Resource List = CDN_URL + /connect.json
        EarlyAuthUrl:
          type: string
          description: The URL of the Early Auth Frontend
        Verified:
          type: boolean
          description: State of Server verification. (A Server needs a certain amount of Players for that over a big timespan)
        UseCdn:
          type: boolean
          description: State of Server CDN
        UseEarlyAuth:
          type: boolean
          description: State of EarlyAuth Authentication of a Server.
        Promoted:
          type: boolean
          description: A Server needs at least a Diamond Altruist Membership.
        Tags:
          type: array
          items:
            type: string
            description: Server tags, e.g. "No Rules"
        UseVoiceChat:
          type: boolean
          description: State of Server Voice Chat
        Level:
          type: integer
          description: The Server's alt:V Version.
        Version:
          type: string
          description: The Server's alt:V Version.
    
    ServerList:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            pattern: '^[0-9]{1,}$'
            description: The Server ID
          name:
            type: string
            description: The Server Name
          locked:
            type: integer
            pattern: '^(0)|(1)$'
            description: State of Server password protection.
          gameMode:
            type: string
            description: The Server Game mode
          language:
            type: object
            properties:
              full:
                type: string
                description: Language e.g. "German", "English"
              short:
                type: string
                description: Language e.g. "de", "en"
          official:
            type: integer
            pattern: '^(0)|(1)$'
            description: State of Server verification. (A Server needs a certain amount of Players for that over a big timespan)
          verified:
            type: integer
            pattern: '^(0)|(1)$'
            description: State of Server verification. (A Server needs a certain amount of Players for that over a big timespan)
          promoted:
            type: integer
            pattern: '^(0)|(1)$'
            description: A Server needs at least a Diamond Altruist Membership.
          tags:
            type: array
            items:
              type: string
            description: Server tags, e.g. "No Rules"
            
    ServerStats:
      type: object
      properties:
        ServerCount:
          type: integer
          description: The Amount of Servers online
        PlayerCount:
          type: integer
          description: The Amount of Players online
        TimeStamp:
          type: string
          format: date-time
          description: Timestamp of the Stats

servers:
  - url: https://api.altstats.net
  - url: http://api.altstats.net
