name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Generate Swagger UI
        uses: Nickwasused/swagger-ui-action@v1
        with:
          output: swagger-ui
          swagger-config-file: swagger-config.json
          
      - name: Copy .yaml file
        run: |
          cp ./altv.yaml swagger-ui
          cp ./altv_u.yaml swagger-ui

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
